Master staging
Kiloma-Advanced-Solutions/kiloma_components pull request #33
Opened 2023-03-27 11:57 UTC by RazSherf

Adding all the last changes

2023-03-28 11:00 UTC, EkingIsrael requested changes
Please sit with me at 14:35 @RazSherf 
We'll discuss this code review.

2023-03-28 11:47 UTC, RazSherf commented on components/numberInput/NumberInputComponent.module.css
> +font-family:  Helvetica;
Ok, i changed it in the code 
this is the full font name :     font-family:  Arial, Helvetica, sans-serif;

2023-03-28 11:48 UTC, RazSherf commented on components/numberInput/NumberInputComponent.jsx
> +              <div className={cx({ [styles.disabled]: Disabled }, [styles.plus_input_button])} role="button" onClick={addValue} tabIndex={0} onKeyUp={() => {}}>^</div>
Ok. next time ill check with you before 👍🏼

2023-03-29 11:18 UTC, RazSherf commented
adding the last changes

2023-04-03 09:53 UTC, EkingIsrael approved these changes

2023-04-03 09:53 UTC, merged